### ISSUE TITLE
No such file or directory: './out/lidar_20Hz/results_nusc.json' when running scripts/ann_generator.sh

### ISSUE THREAD

**Issue by weimzh** [JeffWang987/ASAP#6]
Hi,

I was following the procedure as described [here](https://github.com/JeffWang987/ASAP/blob/main/docs/prepare_data.md), however I got the following exception:

```
# bash scripts/ann_generator.sh 12 --ann_strategy 'interp' 
Traceback (most recent call last):
  File "/root/miniconda3/envs/magicdrive/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/magicdrive/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/disk1/ASAP/sAP3D/nusc_annotation_generator.py", line 357, in <module>
    nusc_20Hz_rst = mmcv.load(opts.lidar_inf_rst_path)
  File "/root/miniconda3/envs/magicdrive/lib/python3.8/site-packages/mmcv/fileio/io.py", line 57, in load
    with StringIO(file_client.get_text(file)) as f:
  File "/root/miniconda3/envs/magicdrive/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 1006, in get_text
    return self.client.get_text(filepath, encoding)
  File "/root/miniconda3/envs/magicdrive/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 535, in get_text
    with open(filepath, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: './out/lidar_20Hz/results_nusc.json'
loading nuscenes dataset...
loading 20Hz LiDAR inference results...
```

are there any instructions on how I can generate or download this file?

thanks in advance.

**Comment by yancx8** [comment]
I meet the same problem, have you solven it?

**Comment by eotich32** [comment]
same problem, need some help

**Comment by eotich32** [comment]
just comment this line:  nusc_20Hz_rst = mmcv.load(opts.lidar_inf_rst_path), then it works
this line is just not used

**Comment by NuanBaobao** [comment]
I also meet the same problem, have you solven it?
